dist: trusty
sudo: require
language: cpp
compiler: gcc

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-5
      - g++-5
      - libgmp3-dev

install:
  - version=3.16
  - build=3
  - mkdir ~/temp
  - cd ~/temp
  - wget https://cmake.org/files/v$version/cmake-$version.$build.tar.gz
  - tar -xzvf cmake-$version.$build.tar.gz
  - cd cmake-$version.$build/
  - ./bootstrap
  - make -j4
  - sudo make install
  - cmake --version

script:
  - sudo ln -s /usr/bin/gcc-5 /usr/local/bin/gcc
  - sudo ln -s /usr/bin/g++-5 /usr/local/bin/g++
  - gcc -v && g++ -v && cmake --version
  - export CC=/usr/bin/gcc-6
  - export CXX=/usr/bin/g++-6
  - cd ${TRAVIS_BUILD_DIR}
  - mkdir build
  - cd build
  - cmake ..
  - make
  - ./psychic-garbanzo test